### ISSUE TITLE
Devanagri package

### ISSUE THREAD

**Issue by alexander-myltsev** [lzanini/mdbook-katex#102]
Hi! There is [a way](https://tex.stackexchange.com/questions/408326/using-devanagri-package-in-latex) to render Devanagri in LaTeX. Do you think it's possible to render it with `mdbook-katex`?

**Comment by SichangHe** [comment]
Hi @alexander-myltsev, I think this is well out of KaTeX's scope into general LaTeX's territory. Feel free to correct me if I'm wrong, though.
