### ISSUE TITLE
Scrollable equations

### ISSUE THREAD

**Issue by lieskjur** [lzanini/mdbook-katex#104]
Would it be possible to make equations that are two long "scrollable" without hosting my own css?

One big advantage of mdbook, in comparison to pdf files, is that I can scale the page to the size of my screen. Unfortunately by default `mdbook-katex` does not do this. The fix is rather simple and even described in the [CSS customization](https://katex.org/docs/issues#css-customization) section of KaTeX's documentation. All that has to be done is to make a single modification to `katex.css`
```
.katex-display { overflow: auto hidden }
```

I wanted to ask if adding it by default or as an option to `mdbook-katex` would be worth considering. It's a bit of a hassle, downloading the css and font just for this...

**Comment by SichangHe** [comment]
I imagine that the easiest way is to have an `additional-css` file with

```css
.katex-display { overflow: auto hidden !important; }
```

Could you please try this, and if it doesn't work, research a bit on how to use CSS?

**Comment by lieskjur** [comment]
Cool, it works.

I have no real experience with css or html but I could have figured, that you can simply add css like this.

Thank you.
