### ISSUE TITLE
Debugging the plugin

### ISSUE THREAD

**Issue by alexander-myltsev** [lzanini/mdbook-katex#105]
Hi. I'm new to Rust. let me know if there's any better place to ask this question.

I'd like to debug the `katex` plugin in an Intellij IDE. How should I run the `mdbook build` command with plugged-in `mdbook-katex` on a real book so that the IDE might catch the breakpoint?

**Comment by SichangHe** [comment]
mdBook calls `mdbook-katex` via the shell when it needs it, which spawns child processes running mdBook-KaTeX. Input and output are handled using the old-school Stdio.

I don't know what you mean by "the `katex` plugin", but I hope my information helps.

**Comment by alexander-myltsev** [comment]
The plugin because `mdbook` authors [call those](https://github.com/rust-lang/mdBook/wiki/Third-party-plugins).

Got that now. I thought `katex` is attached somehow on binary level to `mdbook`. But seems like [all ways to interact](https://rust-lang.github.io/mdBook/for_developers/index.html) with `mdbook` are done via `std in/out`.

Thanks for the explanation!
