### ISSUE TITLE
`\\` line separators invalid in matrix environments

### ISSUE THREAD

**Issue by Dewedseed** [lzanini/mdbook-katex#106]
Hello. I got a issue when using some matrix environment (`matrix` `pmatrix` `bmatrix` `vmatrix` etc.)  The  `\\` line separators seems to be invalid. 

For example:
```
$$\begin{pmatrix}
   a & b & c \\
   c & d & e \\
\end{pmatrix}$$
```
Rendering result: `(a  b  c c  d  e)`

And `\cr` does work but i have to make a lot of modifications. Is there any way to solve this problem? I will be grateful for your reply.

**Comment by SichangHe** [comment]
What I get:

![image](https://github.com/lzanini/mdbook-katex/assets/84777573/50cbda57-622f-4acf-a1d6-c5edc218387a)

Could you provide OS, versions, how you got mdBook-KaTeX?

**Comment by Dewedseed** [comment]
I used the Windows OS and got it from Github. Here is the version information:

- mdBook (mdbook-v0.4.36-x86_64-pc-windows-msvc.zip) [https://github.com/rust-lang/mdBook/releases](https://github.com/rust-lang/mdBook/releases)
- mdBook-KaTeX (mdbook-katex-v0.5.9-x86_64-pc-windows-msvc.zip) [https://github.com/lzanini/mdbook-katex/releases/tag/v0.5.9](https://github.com/lzanini/mdbook-katex/releases/tag/v0.5.9)

I added the path of .exe files to the environment variable and then created a simplest book by commands `mdbook init` and `mdbook serve --open`.

- book.toml

```toml
[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "testbook"

[output.html]
mathjax-support = true

[preprocessor.katex]
after = ["links"]
```
- chapter_1.md

```md
# Chapter 1

$$\begin{pmatrix}
   a & b & c \\
   c & d & e \\
\end{pmatrix}$$
```

What I get in Microsoft Edge:

![katex](https://github.com/lzanini/mdbook-katex/assets/94445615/e52d2919-7303-49cf-8b52-19bdfed14fe5)

It also doesn't work when copying the .exe files to the path. Is there anything wrong with my computer :sob:

**Comment by SichangHe** [comment]
Could you please read this: https://github.com/lzanini/mdbook-katex?tab=readme-ov-file#windows-users

**Comment by Dewedseed** [comment]
Oh, I didn't notice this and made the mistake. I used to think that mdbook-katex needed to use the same version as mdbook.  
Thank you very much!   💓

**Comment by SichangHe** [comment]
Ah, no, the problem is that you should use the GNU build.

**Comment by Dewedseed** [comment]
Yes, it does work normally now. Thank you again for your help.

![katex](https://github.com/lzanini/mdbook-katex/assets/94445615/90aa8601-2111-4577-9959-d52922c37bfc)

**Comment by SichangHe** [comment]
You're welcome.
