### ISSUE TITLE
Macros can't be located when running mdbook with a path

### ISSUE THREAD

**Issue by str4d** [lzanini/mdbook-katex#11]
## Setup

- mdbook config is at `./book/book.toml`
- Book source is at `./book/src`
- Macros file is at `./book/macros.txt`

Config sets paths relative to `./book`:
```toml
[book]
src = "src"

[preprocessor.katex]
macros = "macros.txt"
```

## What did I do

```
$ mdbook build book/
$ cd book/
$ mdbook build ./
```

## Expected result

Both builds succeed.

## Actual result

The first build fails with:
```
$ mdbook build book/
2021-05-27 19:01:18 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'couldn't open macros.txt: No such file or directory (os error 2)', /home/str4d/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-katex-0.2.8/src/lib.rs:151:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-05-27 19:01:18 [ERROR] (mdbook::utils): Error: The preprocessor exited unsuccessfully
```
The second build succeeds.

**Comment by str4d** [comment]
If I change `book.toml` to contain `macros = "book/macros.txt"` then the first build succeeds and the second build fails.

**Comment by kknives** [comment]
I have issued a PR which will fix this issue. Please check if the issue has been resolved.

**Comment by kknives** [comment]
As the PR has been merged, you can use the following `book.toml` by building (I recommend a `release` build) from `master` and then specifying a custom command:
```toml
[book]
src = "src"

[preprocessor.katex]
command = "path/to/build/target/release/mdbook-katex"
macros = "macros.txt"
```
Atleast until a new version is shipped to crates.io

**Comment by lzanini** [comment]
The new version is published on crates.io, @str4d let us know if this fixes your issue.

**Comment by str4d** [comment]
After updating both `mdbook` and `mdbook-katex`, this issue is indeed resolved for me. Thanks!
