### ISSUE TITLE
katex don't work with mdbook fram crates.io

### ISSUE THREAD

**Issue by Vertecedoc4545** [lzanini/mdbook-katex#18]
Error: Katex preprocessor/renderer using different mdbook version, 0.4.13,than it was built against, 0.4.12
i tryed with cargo install mdbook and cargo install mdbook --vers 0.4.12 with neither works

**Comment by Vertecedoc4545** [comment]
linux kernel 5.14.8-zen

**Comment by SichangHe** [comment]
You need to rebuild mdbook-katex against the latest mdbook

first, update mdbook, then

```shell
cargo install --git "https://github.com/lzanini/mdbook-katex" -f
```
