### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by Melind4** [lzanini/mdbook-katex#20]
Add a license file. So that your program can be packaged in the termux repository.

**Comment by olorin37** [comment]
Yep, it is lacking. So, it blocks contributions in fact ...

**Comment by olorin37** [comment]
OK, I found that it is in `Cargo.toml` file defined as MIT license, so as understand license is actually chosen but only License files is lacking...

**Comment by lzanini** [comment]
Hi, I've added the MIT license file
