### ISSUE TITLE
mdbook-katex crashes when `SUMMARY.md` includes empty chapters

### ISSUE THREAD

**Issue by cafce25** [lzanini/mdbook-katex#24]
While writing a book the mdbook tutorial shows the option to have chapters appear in the summary while no files for them beeing created yet by using `- [chapter]()` but mdbook-katex expects every chapter to have a file.

A simple solution could be to simply don't do anything if a chapter doesn't have a path.

<details><summary>backtrace</summary>

```
2022-03-10 16:15:48 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:106:83
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: mdbook::book::book::for_each_mut
   4: <mdbook_katex::KatexProcessor as mdbook::preprocess::Preprocessor>::run
   5: mdbook_katex::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-03-10 16:15:48 [ERROR] (mdbook::utils): Error: The "katex" preprocessor exited unsuccessfully with exit status: 101 status
```
</details>

**Comment by cafce25** [comment]
I think I found a solution and will submit a PR shortly if it works after testing it a bit.

**Comment by cafce25** [comment]
So I couldn't get it to work here maybe due to another issue or me not being familiar enough with mdbook.
I think fixing this should be as simple as replacing
[lines 105-112 in lib.rs](https://github.com/lzanini/mdbook-katex/blob/a16a13f4358cf67db5570ecff5e1002578c161d5/src/lib.rs#L105-L112)
with something like
```rust
if let Some(path) = chapter.path.as_ref() {
    let stylesheet_header = stylesheet_header_generator(path_to_root(path));
    …
}
```

but i seem to be missing something still.

**Comment by ayoubelmhamdi** [comment]
@lzanini could you fix this `bug` in next release!

And thanks, for awesome work.

**Comment by SichangHe** [comment]
Should have been fixed.
