### ISSUE TITLE
error when trying to perform "mdbook build"

### ISSUE THREAD

**Issue by man-chi** [lzanini/mdbook-katex#27]
I have just tried to install and build from the latest version but encounted an error, any idea?   thanks in advance

$ mdbook build                                                 
2022-05-27 00:52:15 [INFO] (mdbook::book): Book building has started
^[[Athread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:106:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-05-27 00:52:16 [ERROR] (mdbook::utils): Error: The "katex" preprocessor exited unsuccessfully with exit status: 101 status

**Comment by SichangHe** [comment]
Please tell me how to reproduce?

**Comment by SichangHe** [comment]
I think this is the same problem as https://github.com/lzanini/mdbook-katex/issues/24.

**Comment by SichangHe** [comment]
I have removed that `unwrap` so this should now be impossible.
