### ISSUE TITLE
Copy/save button near the equations

### ISSUE THREAD

**Issue by Belyor** [lzanini/mdbook-katex#31]
Is it possible to create a buttons near the equation (just like in code listings) that would copy equation code, save the equation image and whatever one would imagine to do with the equation?

To clarify this is what I mean (ofcourse the icons are just copy paste from rust listings and does not correspond to the idea):
![image](https://user-images.githubusercontent.com/36810933/179936364-0e77353f-f507-4de9-87b8-292aafd200cb.png)

**Comment by SichangHe** [comment]
I added an option `include-src` to include the math source code as `span`s. See the README for more information.

Are you able to implement the JavaScript and CSS to create the copy button that you want?

**Comment by SichangHe** [comment]
I have implemented "click to copy source" in [my notes](https://github.com/SichangHe/notes). I think it works fine.

The JavaScript is

```javascript
const math_srcs = document.querySelectorAll("span.katex-src");
document.querySelectorAll("span.katex").forEach((math, index) => {
    const math_src = math_srcs[index];
    math.title = "Click to copy source.";
    math.addEventListener(
        "click",
        () => navigator.clipboard.writeText(math_src.innerText),
    );
})
```

And the CSS is

```css
span.katex {
    cursor: pointer;
}
span.katex-src {
    display: none;
}
```

I am closing this issue now because I think the functionality is done.
