### ISSUE TITLE
`mdbook-katex2` and thank you

### ISSUE THREAD

**Issue by SichangHe** [lzanini/mdbook-katex#37]
I forked this project and created [`mdbook-katex2`](https://github.com/SichangHe/mdbook-katex2). It is now also on [crates.io](https://crates.io/crates/mdbook-katex2).

Users of `mdbook-katex` are welcomed to use `mdbook-katex2`. It provides the same functionality and I will try to keep it maintained.

I want to thank @lzanini, @Matthewacon, @kknives, @Luni-4, @lovesegfault, @srevinsaju and all the other people who helped with `mdbook-katex`. I will try to continue your good work. Please criticize if you wish.

**Comment by SichangHe** [comment]
@lzanini thank you for responding! Sorry for thinking that you are not around…
It would be nicer if you can contact me via email: stevensichanghe@gmail.com
I don't check Twitter despite having an account.

**Comment by SichangHe** [comment]
I have received neither message on Twitter nor email 😔. I will continue to assume that you are too busy to attend to.
Meanwhile, I will do what I can do in `mdbook-katex2`.

**Comment by lzanini** [comment]
Let's merge your changes and update the CI afterwards if needed !

**Comment by SichangHe** [comment]
I have started to maintain `mdbook-katex` and deprecated `mdbook-katex2`.
For future people, please continue to use `mdbook-katex`.
