### ISSUE TITLE
Path to katex.min.css should stay relative

### ISSUE THREAD

**Issue by HadrienG2** [lzanini/mdbook-katex#49]
In commit https://github.com/lzanini/mdbook-katex/commit/647f20c5f708def089843cfc820c8a78cd748268 , the path to katex.min.css was made absolute, so it is now /katex/katex.min.css always.

But that seems wrong for at least two reasons :

1. The path is incorrect in practice. In my builds, the root /katex folder is empty, with resources actually being saved to /html/katex/ . This also begs the question : do you still need the /html root folder to begin with, or could you perhaps go back to the standard mdbook hierarchy, with "katex" becoming a subdirectory of the book ?
2. The generated book may be a subpage of a larger website, and in that situation relative links work better. So if you can afford for links to stay relative, it's probably best to do so.

**Comment by SichangHe** [comment]
> 1. The path is incorrect in practice. In my builds, the root /katex folder is empty, with resources actually being saved to /html/katex/ . 

The path is not incorrect… if you see `/html` as the actual root of the book. `/katex` is just a dummy directory, just like `mdbook-katex` has a dummy `renderer`, at least this is what I understand from the comments left in the source code.
>This also begs the question : do you still need the /html root folder to begin with, or could you perhaps go back to the standard mdbook hierarchy, with "katex" becoming a subdirectory of the book ?

I have [the same question](https://github.com/lzanini/mdbook-katex/issues/48). I want to remove `/html` and `/katex` and have the actual book at `/`.
> 2. The generated book may be a subpage of a larger website, and in that situation relative links work better. So if you can afford for links to stay relative, it's probably best to do so.

You are right. I will fix it.

**Comment by HadrienG2** [comment]
Thanks! I can confirm that my fancy equations work again as expected :)
