### ISSUE TITLE
Add following info to README

### ISSUE THREAD

**Issue by mschoenebeck** [lzanini/mdbook-katex#59]
See https://github.com/rust-lang/mdBook/issues/1984 which I accidentally opened in the mdbook repo (instead of here).

This would be valuable information for newbies which should be mentioned [here](https://github.com/lzanini/mdbook-katex#getting-started).

**Comment by SichangHe** [comment]
Good catch! Make a Pull Request and I will merge it soon.

**Comment by mschoenebeck** [comment]
Here it is: https://github.com/lzanini/mdbook-katex/pull/60

**Comment by SichangHe** [comment]
Thank you @mschoenebeck for your contribution! 🎉
