### ISSUE TITLE
Gitlab style syntax support

### ISSUE THREAD

**Issue by Progdrasil** [lzanini/mdbook-katex#6]
Would it be possible to support [Gitlab style syntax](https://docs.gitlab.com/ee/user/markdown.html#math)? I have some documentation that is hosted using mdBook and on a gitlab repo. I would like to be able to have them render similarly together. 

for example the inline math in gitlab is 
```
$`\frac{x}{y}`$
```
and for blocks
````
```math
\frac{x}{y}
```
````

**Comment by lzanini** [comment]
I'd rather keep things simple and have a single syntax for equations. However, a simple way to achieve what you want would be to use the [mdbook-regex](https://crates.io/crates/mdbook-regex) preprocessor to turn your gitlab math into katex math with regular expressions (which shouldn't be too hard), and then use this preprocessor to render equations.

**Comment by Progdrasil** [comment]
Fair enough, thanks for workaround, I'll look into it.

**Comment by lieskjur** [comment]
I'm trying to implement your recommended solution but there seems to be an issue where the replaced code is not proccessed by the katex preprocessor.

Into the `book.toml` I added
```toml
[preprocessor.katex]
[preprocessor.regex]
patterns = "math.json"
before = [ "katex" ]
```
with the contents of `math.json` being
```json
[
	{
		"pattern" : "```math\\n([^`]*)\\n```",
		"template" : "\\$\\$\\$1\\$\\$"
	},
	{
		"pattern" : "\\$`([^`]*)`\\$",
		"template" : "\\$\\${1}\\$"
	}	
]
```
(probably not perfect the expressions but good enough for me now). The file
```markdown
Controllability
===============

A system is controllable if there exists a sequence of inputs $\bm{u}$ such that the system's state converges to any desired state $`\bm{x}`$.

The state of a linear system
$$
\dot{\bm{x}} = \bm{A}\bm{x} + \bm{B}\bm{u}
$$
can be expressed as
```math
\bm{x}(t) = \int_0^t e^{\bm{A}(t-τ)} \bm{B} \bm{u}(τ)\ dτ
```end
assuming $`\bm{x}(0) = \bm{0}`$
```
(ignore the "end", without it github breaks up the code block) then renders as
![image](https://user-images.githubusercontent.com/61360439/183772600-2223a283-e219-4f6d-acfb-d7478bc4230f.png)
