### ISSUE TITLE
`mdbook build` hangs forever if \$ is in a formula

### ISSUE THREAD

**Issue by llllvvuu** [lzanini/mdbook-katex#61]
Reproduce:
```
We randomly assign: $r \xleftarrow{\$} G $.
We randomly assign: $r \xleftarrow{\\$} G $.
```

Expected:
We randomly assign: $r \xleftarrow{\\$} G $

Actual:
Neither expression works. The `\\$` produces a new line followed by ending the expression. The `\$` causes the preprocessor to hang forever.

I believe the issue stems from https://github.com/lzanini/mdbook-katex/blob/master/src/lib.rs#L456 :
```
self.index += self.string[self.index..].find(&delim.right).ok_or(())?;
```
I'll try to fix...

**Comment by SichangHe** [comment]
The first case should work after I fix it.
The second case is already working as intended. The `\\` indicates that the following `$` should not be escaped and should be seen as the right delimiter for this inline math block.
Let me know if you have different opinions.

**Comment by SichangHe** [comment]
Thank you, @llllvvuu, for catching what I messed up! 🎉
