### ISSUE TITLE
Test the cross-compiled Windows GNU build

### ISSUE THREAD

**Issue by SichangHe** [lzanini/mdbook-katex#67]
I wish someone on Windows can test the GNU build to see if it works correctly. The build is available starting from [Release v0.3.7](https://github.com/lzanini/mdbook-katex/releases/tag/v0.3.7).

In #66, #65, #64, I added CD to cross compile `x86_64-pc-windows-gnu`, `aarch64-apple-darwin` and `x86_64-unknown-linux-musl`. I am confident that the macOS and the MUSL build would work, as I have corresponding CIs for them. The Windows GNU build, however, could not simply be tested using `cargo` due to crossing from Linux to Windows.

The Windows GNU build is also special for windows users because it is currently the only Windows build that uses `quick-js` for `katex` instead of `duktape` and does not have the issue mentioned in #39. Making this GNU build locally on a Windows machine is not easy, so this build in the release would likely be the best choice for Windows users if it works.

**Comment by hwf1324** [comment]
你好，简单的尝试了一下。抱歉的是它并没有在 Windows 上成功构建。

```bash
error: failed to run custom build command for `libquickjs-sys v0.9.0`
```

顺便，目前的版本似乎与 mdbook v0.4.27 不兼容：

```cmd
This mdbook-katex was built against mdbook v0.4.26, but we are being called from mdbook v0.4.27. If you have any issue, this might be a reason.
```

**Comment by SichangHe** [comment]
> 你好，简单的尝试了一下。抱歉的是它并没有在 Windows 上成功构建。
> 
> ```shell
> error: failed to run custom build command for `libquickjs-sys v0.9.0`
> ```

The purpose is not to build the GNU build on Windows but rather to provide a binary which you can find in `Release`.
That said, I would like to know which steps you took to make the build fail.

> 顺便，目前的版本似乎与 mdbook v0.4.27 不兼容：
> 
> ```batchfile
> This mdbook-katex was built against mdbook v0.4.26, but we are being called from mdbook v0.4.27. If you have any issue, this might be a reason.
> ```

The warning about the version mismatch can be ignored as long as the binary works. I did not update `mdbook-katex` to use `mdbook` v0.4.27 because it was merely a rollback "update."

**Comment by hwf1324** [comment]
抱歉，我没能很好阅读说明。
是的，现在 https://github.com/lzanini/mdbook-katex/issues/39 的示例已经成功工作。
真是太棒了！

> That said, I would like to know which steps you took to make the build fail.

```bash
stable-x86_64-pc-windows-gnu (directory override for 'D:\mdbook\mdbook-katex')
```

**Comment by SichangHe** [comment]
> 抱歉，我没能很好阅读说明。 是的，现在 #39 的示例已经成功工作。 真是太棒了！

Thank you very much for testing it out. It is indeed great that it fully works.

> > That said, I would like to know which steps you took to make the build fail.
> 
> ```shell
> stable-x86_64-pc-windows-gnu (directory override for 'D:\mdbook\mdbook-katex')
> ```

Yes, I know the `stable-x86_64-pc-windows-gnu` does not build on Windows. That is why I had to make it cross compile in CI and it took me so long to produce this solution.
