### ISSUE TITLE
equation in {{#include}} not rendered

### ISSUE THREAD

**Issue by expikr** [lzanini/mdbook-katex#79]
Steps to reproduce:

> src.md
>````
> ## My equation
> $$
> E=mc^2
> $$
>````

> ch1.md
> ````
> # Chapter 1
> {{#include src.md}}
> ````

> SUMMARY.md
> ````
> [original](./src.md)
> [included](./ch1.md)
> ````

**Comment by SichangHe** [comment]
Any idea on how to solve this?

I have known this problem for a while. We had to work around it by not using `#include`.

**Comment by SichangHe** [comment]
> Perhaps you should just rip a snapshot of the KaTeX code used to render the equations and put it among the output files, then insert into every page an #include referencing the local snapshot?

I don't think I understand what you are saying here. What is "a snapshot of the KaTeX code used to render the equations?"

> A clientside fallback for "catching" edgecases that didn't get serverside-rendered by the preprocessor.
This is a horrible hack that the users might be okay with.

**Comment by SichangHe** [comment]
> Speaking of which, what's wrong with mdbook-katex just ripping the css automatically anyways when the no-css flag is set?

What do you mean by "ripping the css?" Do you mean that we include the CSS in the binary and directly write it?

> I don't think there are any license restrictions preventing you from just distributing the js and css snapshot in the output?

The problem about licenses would probably be on the fonts.

---

These should be for another issue.

**Comment by SichangHe** [comment]
I need to read the `mdbook` source code to see why `#include` is handled after external preprocessors. That would be the solution.

**Comment by SichangHe** [comment]
I found the solution:

```toml
[preprocessor.katex]
after = ["links"]
```

I will update the README.

**Comment by SichangHe** [comment]
@expikr, please validate whether this solution works.

**Comment by SichangHe** [comment]
> works, thanks!

Great!
> Is there any consideration preventing this from being made the default?

This is controlled by mdBook's behavior. By default, mdBook runs external preprocessors such as `katex` before its internal preprocessors such as `links` which handles `#include`. The `after` option can be used to specify the order.

Does that answer your concern?

**Comment by SichangHe** [comment]
Your proposal does not work to my knowledge, unfortunately. We can only have defaults if the option is for `mdbook-katex`, but in this case, the option is for mdBook.

Options are read by mdBook. mdBook then passes these options to preprocessors such as `mdbook-katex`, where `mdbook-katex` would read options such as `block-delimiter`, so we can have a default in `mdbook-katex` there.

`after` is an option handled by mdBook itself instead of `mdbook-katex`. mdBook uses `after` and `before` to decide the order it calls the preprocessors, which is beyond any preprocessors' control.

Is that clear?

**Comment by SichangHe** [comment]
Yes. Preprocessors can, in fact, only output `book` (content) not `cfg` (configuration) to mdBook.

mdBook has rather poor documentation on these topics, sadly. I had to read the mdBook source code to make some parts in `mdbook-katex` functioning.
