### ISSUE TITLE
the table will have only one column if continuous math expressiones is in table colums

### ISSUE THREAD

**Issue by imxood** [lzanini/mdbook-katex#8]
### this is wrong
```
|  header1   | header2  |
|  ----  | ----  |
| $\omega$     | $\omega$ |
```

### this is good after adding any a symbol after $
```
|  header1   | header2  |
|  ----  | ----  |
| $\omega$.     | $\omega$ |
```
![image](https://user-images.githubusercontent.com/14890680/113982021-ddd3a800-987a-11eb-9b31-030fbd4b7df4.png)

**Comment by kknives** [comment]
This seems to have been fixed:
```
| Syntax | Description |
| --- | ----------- |
| $\omega$ | $\omega$ |
| Paragraph | Text |
```
![image](https://user-images.githubusercontent.com/57328978/121541530-03b92c80-ca25-11eb-9dbf-91282cb6553f.png)
