### ISSUE TITLE
pmatrix not working

### ISSUE THREAD

**Issue by expikr** [lzanini/mdbook-katex#80]
![image](https://user-images.githubusercontent.com/77922942/230729316-3a05bcda-daf2-4947-aa8a-6eb1cc21e719.png)

**Comment by SichangHe** [comment]
Which `mdbook-katex` binary are you using?

I think this may be related to https://github.com/lzanini/mdbook-katex/issues/67#issue-1574295945 paragraph 3. Does that help?

**Comment by SichangHe** [comment]
Please use the GNU Windows build if possible. It is larger in size at the moment but it has the full functionality.
