### ISSUE TITLE
`include-src` breaks if latex source is double-spaced

### ISSUE THREAD

**Issue by expikr** [lzanini/mdbook-katex#81]
To reproduce, enable include-src and add an equation with extra linebreaks within the $$ block.

It seems that html quotations doesn't close properly when there are extra linebreaks.

Suggestion: minify the included source by removing the linebreaks.

```
# Chapter 1

$$
\begin{aligned}

f(t) = \int_{-\infty}^{\infty} F(\omega) e^{2\pi i\omega t} d\omega \\

F(\omega) = \int_{-\infty}^{\infty} f(t) e^{-2\pi i\omega t} dt 

\end{aligned}
$$
```

![image](https://user-images.githubusercontent.com/77922942/230766326-3ae2083b-7f0d-4c0a-8a55-15b8375a95a5.png)

**Comment by SichangHe** [comment]
This is because mdBook, when parsing
```html
<data class="katex-src" value="
A

B
"><span class="katex-display">…<span>
```
identifies the two newlines between `A` and `B` as a new paragraph and injects `<p>` between them.
