### ISSUE TITLE
Possibility of serverside TikZJax rendering?

### ISSUE THREAD

**Issue by expikr** [lzanini/mdbook-katex#83]
Just as mdbook-katex leverages existing KaTeX javascript, the same structuring could apply to the existing [obsidian-tikzjax](https://github.com/artisticat1/obsidian-tikzjax) javascript implementation which is run clientside to generate html outputs, all we would need to do is to feed it the markdown input during the preparse time and it becomes serverside rendering.

If the use of ` ```tikz ` blocks is a potential issue, a custom tag could always be used instead as the default i.e. `<tikz></tikz>`, though I guess since mdbook-mermaid is a thing this wouldn't be a problem.

**Comment by SichangHe** [comment]
Feel free to fork either this repository or mdbook-mermaid for a starting point and implement a preprocessor yourself.

Closing because this is out of bound of this project
