### ISSUE TITLE
option for MathML output

### ISSUE THREAD

**Issue by expikr** [lzanini/mdbook-katex#86]
According to https://katex.org/docs/options.html KaTeX supports MathML outputs enabled by a flag.

Would be nice if a flag could be added that allows the display output to be in MathML, as it is now supported in Chrome since the beginning of this year: https://katex.org/docs/options.html

**Comment by SichangHe** [comment]
This may not be obvious, but it is one of the options we have under [KaTeX options](https://github.com/lzanini/mdbook-katex#katex-options) following what KaTeX offers.

You should be able to do this:

```toml
[preprocessor.katex]
after = ["links"]
output = "mathml"
```
