### ISSUE TITLE
$ symbol in the code block should not be parsed

### ISSUE THREAD

**Issue by imxood** [lzanini/mdbook-katex#9]
it is rendered wrongly in ``` math expressiones ``` code block

for example:
```
``` $\omega$ ```
```
it will is:
![image](https://user-images.githubusercontent.com/14890680/113982932-f0021600-987b-11eb-8d2f-b54a23db1575.png)

**Comment by lzanini** [comment]
What is a math expressiones code block ? I am not sure what you are trying to achieve here

**Comment by imxood** [comment]
> What is a math expressiones code block ? I am not sure what you are trying to achieve here

for example:

![image](https://user-images.githubusercontent.com/14890680/113985100-60119b80-987e-11eb-9524-c540493be2cd.png)

![image](https://user-images.githubusercontent.com/14890680/113985177-77e91f80-987e-11eb-844d-b7c3952d02b4.png)

I expect: the `````` code block is not parsed~
I expect: ``` $x^4$ ``` in code block is kept ~

**Comment by lzanini** [comment]
What is the point of code block quotes then ?

**Comment by imxood** [comment]
> What is the point of code block quotes then ?

It is one of the writing forms of markdown code block

like this:

```
    ```
    int main(int argc, char const *argv[])
    {
        /* code */
        return 0;
    }
    ```

    ``` echo $PATH ```

    ``` $PATH ```

```

**Comment by lzanini** [comment]
Sorry, what I meant was: what is the point of adding code blocks around Tex equations, if what you want to achieve is simply an equation ? And why should "ignore code block" in that situation be the expected behavior ?

If you want to render equation within a code block, I don't think this is possible

**Comment by imxood** [comment]
It should be said that the $ symbol in the code block should not be parsed

here is some $ symbol in the code block, this is parsed wrongly!

![image](https://user-images.githubusercontent.com/14890680/114003790-a2dc6f00-9890-11eb-830b-8ea45d6efc67.png)

![image](https://user-images.githubusercontent.com/14890680/114004198-ffd82500-9890-11eb-90c6-b63fa130c56a.png)

**Comment by lzanini** [comment]
Oh I see. I should be able to fix this, I'll look into it

**Comment by imxood** [comment]
> Oh I see. I should be able to fix this, I'll look into it

Also consider the $ symbol in the code block of tab indentation, which may be a bit difficult

thank you very much~

**Comment by parazyd** [comment]
Any luck fixing this?

**Comment by SichangHe** [comment]
Should have been fixed.

**Comment by HadrienG2** [comment]
This is actually not fixed for \`inline code blocks\`.

**Comment by SichangHe** [comment]
I see. Let me see what I can do.

**Comment by SichangHe** [comment]
This should fix inline code blocks https://github.com/lzanini/mdbook-katex/commit/5efa3869aa4d84869325c42d836349ef1a7e53d4.

**Comment by HadrienG2** [comment]
Thank you !

**Comment by your-diary** [comment]
It seems the problem still exists.

### Markdown

``````
1. hello

    <!-- ` -->

2. world

    `$object->{'id'}`

    ```php
    $object = $another
    ```
``````

### `mdbook`

![Screenshot 2023-10-10 at 19 09 11](https://github.com/lzanini/mdbook-katex/assets/58146437/5c4406e1-aa7d-4c6d-9d1e-f2ba004d75de)

### GitHub

1. hello

    

2. world

    `$object->{'id'}`

    ```php
    $object = $another
    ```
