### ISSUE TITLE
Error: The katex preprocessor does not support the 'pdf' renderer

### ISSUE THREAD

**Issue by GopherJ** [lzanini/mdbook-katex#94]
this happened while using mdbook-pdf, is mdbook-katex missing pdf support?

**Comment by SichangHe** [comment]
Support check only confirms `markdown` and `html`:

https://github.com/lzanini/mdbook-katex/blob/e067f6beeb6cffd6cb51b06fd4e11ba9fb3ba7e6/src/preprocess.rs#L76-L77

If you are interested, you can try removing this method (it has a default implementation that simply returns `true`) and compile this your self.

**Comment by SichangHe** [comment]
Removed the said method in v0.5.8.
