### ISSUE TITLE
Help: matrix not display correctly

### ISSUE THREAD

**Issue by Tramis** [lzanini/mdbook-katex#95]
platform: Windows 10

mdbook & mdbook-katex version:

```bash
> mdbook -V
mdbook v0.4.34
> mdbook-katex -V
mdbook-katex 0.5.7
```

when I wrote a matrix, it didn't display correctly, is there any suggest?
![image](https://github.com/lzanini/mdbook-katex/assets/34150794/d6d45fa4-dd15-46d7-b198-f64b2b37a9c7)
![image](https://github.com/lzanini/mdbook-katex/assets/34150794/bec60766-ba1c-46e8-9545-0adc65e23c85)

**Comment by SichangHe** [comment]
Please read [this part in the README](https://github.com/lzanini/mdbook-katex#getting-started).

Does that answer your questions?

**Comment by Tramis** [comment]
Oh, thanks! I didn't notice the platform issues before, now I use the [mdbook-katex-v0.5.7-x86_64-pc-windows-gnu.zip](https://github.com/lzanini/mdbook-katex/releases/download/v0.5.7/mdbook-katex-v0.5.7-x86_64-pc-windows-gnu.zip) and it works now 😇

**Comment by SichangHe** [comment]
Good to hear that it works! 🙂
