### ISSUE TITLE
Unable to render matrix

### ISSUE THREAD

**Issue by Aye10032** [lzanini/mdbook-katex#96]
![image](https://github.com/lzanini/mdbook-katex/assets/31495549/4ce28e6e-1382-40f1-b258-10ae727cd140)
I used the above LaTeX statement to describe a matrix, but after compilation, I found that it was unable to render successfully while normal formulas can be rendered normally:
![image](https://github.com/lzanini/mdbook-katex/assets/31495549/1b4920dd-c679-4c2e-b5c5-203093614dc7)

**Comment by SichangHe** [comment]
Could you look at #95?

**Comment by Aye10032** [comment]
> Could you look at #95?

Ah, yes, sorry I didn't carefully read the README.
It works now!
